include: package:flutter_lints/flutter.yaml

linter:

  rules:
    - prefer_const_constructors
    - prefer_final_locals
    - prefer_single_quotes

    - avoid_print: false
    - unnecessary_string_interpolations: false