services:
  flutter-dev:
    build:
      context: .
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    container_name: foodstream-mobile-dev
    volumes:
      - .:/app
      - flutter-cache:/opt/flutter-cache
      - pub-cache:/opt/pub-cache
      - gradle-cache:/opt/gradle-cache
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - FLUTTER_WEB_PORT=3000
      - FLUTTER_WEB_HOSTNAME=0.0.0.0
      - PUB_CACHE=/opt/pub-cache
      - FLUTTER_ROOT=/opt/flutter
    working_dir: /app
    tty: true
    stdin_open: true
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"

volumes:
  flutter-cache:
  pub-cache:
  gradle-cache:
