name: foodstream_mobile
description: "A Flutter mobile application for live streaming food preparation and cooking experiences."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0+1
  flutter_dotenv: ^5.2.1
  web: ^1.1.1
  flutter_webrtc: ^0.13.1
  socket_io_client: ^3.1.2
  shared_preferences: ^2.5.2
  http: ^1.4.0
  livekit_client: ^2.4.5
  livekit_components: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
