name: Build APK and Create GitHub Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      apk-path: ${{ steps.upload_artifact.outputs.artifact_path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'  #CHANGE

      - name: Get dependencies
        run: flutter pub get

      - name: Build release APK for Android 15 compatibility
        run: flutter build apk --release --target-platform android-arm,android-arm64,android-x64

      - name: Upload APK artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release.apk

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0       # CHANGE
          name: Release Android 15 compatible APK
          body: |
            Release générée automatiquement via CI/CD pour Android 15.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0
          name: app-release.apk
          asset_path: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
